server:
  port: 5200
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    # 数据库访问配置, 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #基础连接配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myblog?&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: password
    #连接配置
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 连接等待超时时间
    max-wait: 30000
    # 配置检测可以关闭的空闲连接间隔时间
    time-between-eviction-runs-millis: 60000
    # 配置连接在池中的最小生存时间
    min-evictable-idle-time-millis: 300000
    validation-query: select '1' from dual
    test-while-idle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-borrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
    filters: stat
    # Spring监控AOP切入点，如 x.y.z.service.*,配置多个英文逗号分隔
    # aop-patterns: cc.mrbird.*.service.*
    # WebStatFilter配置
  web-stat-filter:
    enabled: true
    # 添加过滤规则
    url-pattern: /*
    # 忽略过滤的格式
    exclusions: '*.js,*.gif,*.ttf,*.woff,*.jpg,*.png,*.css,*.ico,/druid/*,/actuator/*'
    # StatViewServlet配置
  stat-view-servlet:
    enabled: true
    # 访问路径为/druid时，跳转到StatViewServlet
    url-pattern: /druid/*
    # 是否能够重置数据
    reset-enable: false
    # 需要账号密码才能访问控制台
    login-username: druid
    login-password: druid123
    # IP白名单
    # allow: 127.0.0.1
    # IP黑名单（共同存在时，deny优先于allow）
    # deny: 192.168.1.218
    # 配置StatFilter
    filter:
      stat:
        log-slow-sql: true
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
    #热部署
  devtools:
    restart:
      exclude: static/**,public/**
      additional-paths: src/main/java


#通用mapper配置
mapper:
  mappers: cn.cllover.myblog.common.MyMapper
  not-empty: false
  identity: MYSQL

#mybatis配置
mybatis:
  type-aliases-package: cn.cllover.myblog.system.entry
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null

#引入日志配置文件
logging:
  config: classpath:logback-spring.xml
  level:
    cn.cllover.myblog.front.dao: debug

thymeleaf:
#  prefix: classpath:/templates/　
#  suffix: .html
#  #模式
#  mode: HTML5
#  encoding: utf-8
#  content-type: text/html
#  #是否开启缓存
  cache: false


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


