package cn.cllover.myblog.system.pojo;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`myblog_user`")
public class MyblogUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_id
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_pass
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String userPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_name
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_email
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_age
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private Integer userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_display
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String userDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_phone
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private Integer userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_sex
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_photo
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String userPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.login_last_time
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private Date loginLastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_status
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_desc
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String userDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_id
     *
     * @return the value of myblog_user.user_id
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_id
     *
     * @param userId the value for myblog_user.user_id
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_pass
     *
     * @return the value of myblog_user.user_pass
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_pass
     *
     * @param userPass the value for myblog_user.user_pass
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_name
     *
     * @return the value of myblog_user.user_name
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_name
     *
     * @param userName the value for myblog_user.user_name
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_email
     *
     * @return the value of myblog_user.user_email
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_email
     *
     * @param userEmail the value for myblog_user.user_email
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_age
     *
     * @return the value of myblog_user.user_age
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_age
     *
     * @param userAge the value for myblog_user.user_age
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_display
     *
     * @return the value of myblog_user.user_display
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getUserDisplay() {
        return userDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_display
     *
     * @param userDisplay the value for myblog_user.user_display
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserDisplay(String userDisplay) {
        this.userDisplay = userDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_phone
     *
     * @return the value of myblog_user.user_phone
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public Integer getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_phone
     *
     * @param userPhone the value for myblog_user.user_phone
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserPhone(Integer userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_sex
     *
     * @return the value of myblog_user.user_sex
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_sex
     *
     * @param userSex the value for myblog_user.user_sex
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_photo
     *
     * @return the value of myblog_user.user_photo
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getUserPhoto() {
        return userPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_photo
     *
     * @param userPhoto the value for myblog_user.user_photo
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserPhoto(String userPhoto) {
        this.userPhoto = userPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.login_last_time
     *
     * @return the value of myblog_user.login_last_time
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public Date getLoginLastTime() {
        return loginLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.login_last_time
     *
     * @param loginLastTime the value for myblog_user.login_last_time
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setLoginLastTime(Date loginLastTime) {
        this.loginLastTime = loginLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_status
     *
     * @return the value of myblog_user.user_status
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_status
     *
     * @param userStatus the value for myblog_user.user_status
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_desc
     *
     * @return the value of myblog_user.user_desc
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getUserDesc() {
        return userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_desc
     *
     * @param userDesc the value for myblog_user.user_desc
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc;
    }
}