package cn.cllover.myblog.system.pojo;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`myblog_article`")
public class MyblogArticle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_id
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private Long artId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.user_id
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_title
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String artTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_type
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String artType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_tags
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String artTags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_thumbnail
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String artThumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_writetime
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private Date artWritetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_updatetime
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private Date artUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_url
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String artUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_photo
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String artPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_status
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String artStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_content
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String artContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_article.art_content_desc
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    private String artContentDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_id
     *
     * @return the value of myblog_article.art_id
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public Long getArtId() {
        return artId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_id
     *
     * @param artId the value for myblog_article.art_id
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtId(Long artId) {
        this.artId = artId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.user_id
     *
     * @return the value of myblog_article.user_id
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.user_id
     *
     * @param userId the value for myblog_article.user_id
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_title
     *
     * @return the value of myblog_article.art_title
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getArtTitle() {
        return artTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_title
     *
     * @param artTitle the value for myblog_article.art_title
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtTitle(String artTitle) {
        this.artTitle = artTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_type
     *
     * @return the value of myblog_article.art_type
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getArtType() {
        return artType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_type
     *
     * @param artType the value for myblog_article.art_type
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtType(String artType) {
        this.artType = artType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_tags
     *
     * @return the value of myblog_article.art_tags
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getArtTags() {
        return artTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_tags
     *
     * @param artTags the value for myblog_article.art_tags
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtTags(String artTags) {
        this.artTags = artTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_thumbnail
     *
     * @return the value of myblog_article.art_thumbnail
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getArtThumbnail() {
        return artThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_thumbnail
     *
     * @param artThumbnail the value for myblog_article.art_thumbnail
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtThumbnail(String artThumbnail) {
        this.artThumbnail = artThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_writetime
     *
     * @return the value of myblog_article.art_writetime
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public Date getArtWritetime() {
        return artWritetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_writetime
     *
     * @param artWritetime the value for myblog_article.art_writetime
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtWritetime(Date artWritetime) {
        this.artWritetime = artWritetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_updatetime
     *
     * @return the value of myblog_article.art_updatetime
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public Date getArtUpdatetime() {
        return artUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_updatetime
     *
     * @param artUpdatetime the value for myblog_article.art_updatetime
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtUpdatetime(Date artUpdatetime) {
        this.artUpdatetime = artUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_url
     *
     * @return the value of myblog_article.art_url
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getArtUrl() {
        return artUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_url
     *
     * @param artUrl the value for myblog_article.art_url
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtUrl(String artUrl) {
        this.artUrl = artUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_photo
     *
     * @return the value of myblog_article.art_photo
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getArtPhoto() {
        return artPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_photo
     *
     * @param artPhoto the value for myblog_article.art_photo
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtPhoto(String artPhoto) {
        this.artPhoto = artPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_status
     *
     * @return the value of myblog_article.art_status
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getArtStatus() {
        return artStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_status
     *
     * @param artStatus the value for myblog_article.art_status
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtStatus(String artStatus) {
        this.artStatus = artStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_content
     *
     * @return the value of myblog_article.art_content
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getArtContent() {
        return artContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_content
     *
     * @param artContent the value for myblog_article.art_content
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtContent(String artContent) {
        this.artContent = artContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_article.art_content_desc
     *
     * @return the value of myblog_article.art_content_desc
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public String getArtContentDesc() {
        return artContentDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_article.art_content_desc
     *
     * @param artContentDesc the value for myblog_article.art_content_desc
     *
     * @mbg.generated Mon Apr 01 11:52:36 CST 2019
     */
    public void setArtContentDesc(String artContentDesc) {
        this.artContentDesc = artContentDesc;
    }
}